version: 0.2
phases:
  pre_build:
    commands:
      - msbuild restore HelloWorldWebApp/HelloWorldWebApp.csproj
  build:
    commands:
      - msbuild publish -c release -o ./build_output HelloWorldWebApp/HelloWorldWebApp.csproj
artifacts:
  files:
    - CodeBuild-HelloWorld/build_output/**/*
